// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy_DP0SQ-RIBkahNtSh-j0boANlEUV6bg',
    appId: '1:882147279928:web:12c2ec2ed43acf274c12cd',
    messagingSenderId: '882147279928',
    projectId: 'fastaapp-3e39a',
    authDomain: 'fastaapp-3e39a.firebaseapp.com',
    storageBucket: 'fastaapp-3e39a.appspot.com',
    measurementId: 'G-QE3T9T6R4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfFqlPfDs8sHiFjnv47lwYuHJS0e6DEw',
    appId: '1:882147279928:android:a90da00e82e537874c12cd',
    messagingSenderId: '882147279928',
    projectId: 'fastaapp-3e39a',
    storageBucket: 'fastaapp-3e39a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbqVPQMnLGYJ9aQM0qRT62ImhUBYw_Aw',
    appId: '1:882147279928:ios:62e71739153014bb4c12cd',
    messagingSenderId: '882147279928',
    projectId: 'fastaapp-3e39a',
    storageBucket: 'fastaapp-3e39a.appspot.com',
    iosClientId: '882147279928-lpedq8c9use9toflua07c2mlt3ji424i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbqVPQMnLGYJ9aQM0qRT62ImhUBYw_Aw',
    appId: '1:882147279928:ios:3fbd817f5169a09a4c12cd',
    messagingSenderId: '882147279928',
    projectId: 'fastaapp-3e39a',
    storageBucket: 'fastaapp-3e39a.appspot.com',
    iosClientId: '882147279928-egd96faord514f2l8ur02j6juqc16fag.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastaApp.RunnerTests',
  );
}
